Stencilbook added to program-tools
saasquatch/program-tools pull request #117
Opened 2021-04-20 18:24 UTC by 00salmon

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

 - Jira issue number: (PUT IT HERE)
 - Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist
- [ ] "Ready for review" label attached to the PR and reviewers pinged on Slack

### Code review 

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2021-04-21 20:54 UTC, 00salmon commented on packages/stencilbook/package.json
> +  "version": "0.0.1-beta6",
```suggestion
  "version": "1.0.0",
```

2021-04-21 21:39 UTC, 00salmon commented on packages/stencilbook/src/stencil-storybook.tsx
> +                              const subStoryView = () => <subStory />;
```suggestion
                              const subStoryView = () => <subStory />;
```
this is never used

2021-04-22 00:45 UTC, loganvolkers commented on packages/stencilbook/src/stencil-storybook.tsx
> +import * as Hooks from "@saasquatch/stencil-hooks";
Should swap to universal hooks

```suggestion
import * as Hooks from "@saasquatch/stencil-hooks";
```

2021-04-22 00:46 UTC, loganvolkers requested changes
Switch to universal hooks

2021-05-26 18:19 UTC, noahwc commented
Added custom homepage with a new `home` prop. Stencilbook initially loads to the homepage and users can return to the homepage by clicking on the header.

2021-05-26 21:49 UTC, loganvolkers commented on packages/stencilbook/package.json
> +    "@saasquatch/stencil-hooks": "^2.0.0",
Not required anymore?

```suggestion
```

2021-05-26 21:49 UTC, loganvolkers requested changes
@00salmon Add a changelog

2021-05-26 22:01 UTC, loganvolkers approved these changes
Looks good to me!

2021-05-26 22:02 UTC, merged