Bedrock Components
saasquatch/program-tools pull request #118
Opened 2021-04-20 23:27 UTC by 00salmon

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

 - Jira issue number: (PUT IT HERE)
 - Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist
- [ ] "Ready for review" label attached to the PR and reviewers pinged on Slack

### Code review 

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2021-04-21 20:54 UTC, 00salmon commented on packages/bedrock-components/package.json
> +  "version": "0.0.2",
```suggestion
  "version": "1.0.0",
```

2021-04-22 00:35 UTC, loganvolkers commented on packages/bedrock-components/package.json
> +  "repository": "https://github.com/saasquatch/program-tools/tree/master/packages/bedrock-components",
@00salmon Repository field isn't quite right

2021-04-22 00:36 UTC, loganvolkers commented on packages/bedrock-components/package.json
> +    "@saasquatch/stencil-grapes-plugin": "^0.1.2",
@00salmon Should use the 1.0 versions

2021-04-22 00:37 UTC, loganvolkers commented on packages/bedrock-components/src/components/sqb-conditional-section/sqb-conditional-section.feature
> +  @review
Remove all the `@review` tags.

```suggestion
```

2021-04-22 00:37 UTC, loganvolkers commented on packages/bedrock-components/src/components/sqb-conditional-section/sqb-conditional-section.feature
> +  @review
Remove all the `@review` tags.

```suggestion
```

2021-04-22 00:43 UTC, loganvolkers requested changes
Version number update and package.json cleanliness

2021-04-22 00:58 UTC, loganvolkers commented on packages/bedrock-components/package.json
> +    "@saasquatch/stencil-grapes-plugin": "^1.0.0",
This should be a dev dependency

```suggestion
    "@saasquatch/stencil-grapes-plugin": "^1.0.0",
```

2021-04-22 01:00 UTC, loganvolkers approved these changes
Looks good to me!

2021-04-22 01:01 UTC, merged