Component boilerplate portal
saasquatch/program-tools pull request #154
Opened 2021-07-08 18:10 UTC by ianhitchcock

## Description of the change

Changes required by the mint portal components in component boilerplate

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

 - Jira issue number: (PUT IT HERE)
 - Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist
- [ ] "Ready for review" label attached to the PR and reviewers pinged on Slack

### Code review 

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2021-07-15 21:00 UTC, johanventer commented on packages/component-boilerplate/src/environment/environment.ts
> +const DEFAULT_PORTAL_AUTH_URL = "https://portal-auth.referralsaasquatch.com"; //todo: finalize
Flagging todo

2021-07-22 22:43 UTC, johanventer requested changes

2021-07-22 22:43 UTC, johanventer commented on packages/component-boilerplate/src/index.ts
> +  usePortalAuthUrl,
Remove

2021-08-03 21:59 UTC, ianhitchcock commented on packages/component-boilerplate/src/environment/environment.ts
> +
Removed :+1:

2021-08-03 21:59 UTC, ianhitchcock commented on packages/component-boilerplate/src/index.ts
> +  usePortalAuthUrl,
Removed :+1:

2021-08-03 22:49 UTC, johanventer submitted a review, later dismissed

2021-08-04 17:26 UTC, johanventer approved these changes

2021-08-04 17:31 UTC, merged