Extension of referral-table and big-stat for classic use
saasquatch/program-tools pull request #166
Opened 2021-08-18 00:39 UTC by Locrian24

## Description of the change

> **big-stat**: Removes the `programId` requirement for `big-stat` stat queries, and enforces not filtering stats by only Classic.
**referral-table**: Adds "classic" option to programId prop to filter on classic only referrals. Also adds ability to hide column labels and style next/prev buttons

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

 - Jira issue number: (PUT IT HERE)
 - Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [x] [Prettier](https://www.npmjs.com/package/prettier) was run
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist
- [ ] "Ready for review" label attached to the PR and reviewers pinged on Slack

### Code review 

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2021-08-23 18:00 UTC, 00salmon commented on packages/mint-components/package.json
>      "@saasquatch/stencil-hooks": "^2.0.1-0",
```suggestion
    "@saasquatch/stencil-hooks": "^2.0.2",
```

2021-08-30 22:51 UTC, loganvolkers commented on packages/mint-components/CHANGELOG.md
> +- \<sqm-big-stat> will return appropriate stats or error for "classic" program id
Height changes should be noted.

```suggestion
- \<sqm-big-stat> will return appropriate stats or error for "classic" program id. Height is inherited
```

2021-08-31 16:40 UTC, loganvolkers commented on packages/mint-components/src/index.html
> +    </sqm-referral-table>
@Locrian24 Never commit this! Add a story with this HTML content instead.

```suggestion
    <sqm-stencilbook></sqm-stencilbook>
```

2021-08-31 16:44 UTC, loganvolkers commented on packages/mint-components/package.json
> +  "version": "1.1.2-12",
Need to update to `1.1.2`.

```suggestion
  "version": "1.1.2-12",
```

2021-08-31 16:46 UTC, loganvolkers commented on packages/mint-components/CHANGELOG.md
> +## [1.1.2] - 2021-08-20
Need to update to `1.2.0` since this adds some new functionality. (see https://semver.org/)

2021-08-31 16:46 UTC, loganvolkers approved these changes
Looks good to me, but should be published as `1.2.0` since it adds bigger functionality (referred you stuff)

2021-08-31 16:49 UTC, loganvolkers commented on packages/mint-components/package.json
> +    "@saasquatch/component-boilerplate": "^1.2.2-0",
Need to update to `1.2.2`

2021-08-31 16:49 UTC, loganvolkers requested changes
Need to wait for this deploy first: https://github.com/saasquatch/program-tools/pull/169

2021-08-31 21:07 UTC, 00salmon commented on packages/mint-components/CHANGELOG.md
> +## [1.2.0] - 2021-08-20
```suggestion
## [1.2.0] - 2021-08-31
```

2021-08-31 21:07 UTC, 00salmon submitted a review, later dismissed
👍

2021-09-15 00:15 UTC, loganvolkers commented on packages/mint-components/package.json
> +    "@saasquatch/component-boilerplate": "^1.2.2-0",
Still needs to be updated

2021-09-15 00:16 UTC, 00salmon commented on packages/mint-components/package.json
> +    "@saasquatch/component-boilerplate": "^1.2.2-0",
```suggestion
    "@saasquatch/component-boilerplate": "^1.2.2",
```

2021-09-15 00:17 UTC, 00salmon commented on packages/mint-components/package.json
> +    "@saasquatch/component-boilerplate": "^1.2.2-0",
done!

2021-09-17 22:45 UTC, loganvolkers commented on packages/mint-components/package.json
> +  "version": "1.1.2-13",
Should be 1.2.0

2021-09-17 22:48 UTC, loganvolkers reviewed
Looks good to me! Needs the NPM and Changelog versions and dates properly set, then can be deployed.

2021-09-18 00:08 UTC, loganvolkers commented on packages/mint-components/CHANGELOG.md
> +- \<sqm-big-stat> will return appropriate stats or error for "classic" program id. Height is inherited
```suggestion
- \<sqm-referral-table> can pull only classic referrals
- \<sqm-referral-table> supports showing "Referred You" row
- \<sqm-referral-table> supports additional props to override text values
- \<sqm-referral-table> has default loading and empty slots
- \<sqm-referral-table> pagination button labels are customizable
- \<sqm-share-button> text slot (default slot) is hideable
- \<sqm-big-stat> will return appropriate stats or error for "classic" program id. Height is inherited
```

2021-09-18 00:08 UTC, loganvolkers approved these changes
Looks good to me

2021-09-18 00:08 UTC, merged