[DEV-3099] component-boilerplate: Support theme engine JWT payloads
saasquatch/program-tools pull request #169
Opened 2021-08-20 22:49 UTC by johanventer

## Description of the change

Classic theme engine themes are provided with a JWT that does not have our standard user JWT payload like:
```json
{
  "user": {
    "id": "xxx",
    "accountId": "xxx"
  }
}
```

Instead they receive JWTs with a payload as follows:
```
{
  "sub": "<base64-encoded accountId>:<base64-encoded userId>@<tenantAlias>:users
}
```

Instead of changing the backend's generation of these JWTs, which could have backwards-incompatible consequences, instead this updates `component-boilerplate` to be able to parse these types of JWTs for extracting user identity.

This makes it possible to use `mint-components` and `component-boilerplate` in "hybrid themes"

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

 - Jira issue number: DEV-3099
 - Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist
- [ ] "Ready for review" label attached to the PR and reviewers pinged on Slack

### Code review 

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2021-08-20 23:17 UTC, loganvolkers requested changes
Needs changelog updated

2021-08-23 17:59 UTC, loganvolkers commented on packages/mint-components/package.json
>      "@saasquatch/stencil-hooks": "^2.0.1-0",
Stencil hooks should be removed.

2021-08-31 16:48 UTC, loganvolkers approved these changes
Looks good to me, please publish as `1.2.2`

2021-08-31 18:00 UTC, slisaasquatch approved these changes

2021-08-31 18:05 UTC, merged