Mint Components: Update Twitter share button to X
saasquatch/program-tools pull request #369
Opened 2024-01-11 22:39 UTC by AndiLuo

## Description of the change

Updated Twitter share button to 'X'. Updated template copies from 'Tweet about us' to 'Post about us on X'.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

- Jira issue number: (PUT IT HERE)
- Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run (if applicable)
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist

### Code review

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2024-01-13 00:16 UTC, noahwc reviewed
Looks good just need to update version/changelog

2024-01-16 18:44 UTC, noahwc submitted a review, later dismissed

2024-02-06 21:44 UTC, Locrian24 requested changes

2024-02-06 21:44 UTC, Locrian24 commented on packages/mint-components/package.json
> +  "version": "1.7.3-0",
```suggestion
  "version": "1.7.3",
```

2024-02-06 21:46 UTC, noahwc submitted a review, later dismissed

2024-09-11 18:14 UTC, noahwc commented on packages/mint-components/src/components/sqm-share-button/sqm-share-button.tsx
> +// ZH TODO: What is the correct copy for share buttons here ? There are some differences in our widget templates
Flagging todo

2024-09-11 22:44 UTC, noahwc approved these changes

2024-09-11 22:44 UTC, zachharrison approved these changes

2024-09-12 21:26 UTC, Locrian24 approved these changes

2024-09-12 21:33 UTC, merged