Tax and cash/fast follows
saasquatch/program-tools pull request #394
Opened 2024-04-11 23:24 UTC by zachharrison

## Description of the change

> Change direction of tooltip to avoid popover from getting cut off. 

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

### Development

- [X] [Prettier](https://www.npmjs.com/package/prettier) was run (if applicable)
- [X] The behaviour changes in the pull request are covered by specs
- [X] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist

### Code review

- [X] Changes have been reviewed by at least one other engineer
- [X] Security impacts of this change have been considered

2024-04-12 18:22 UTC, noahwc approved these changes

2024-04-12 18:23 UTC, noahwc requested changes
Just some changelog cleanup!

2024-04-12 18:23 UTC, noahwc commented on packages/mint-components/CHANGELOG.md
> +## [Unreleased]
Remove the extra unreleased

2025-05-27 20:59 UTC, 00salmon submitted a review, later dismissed
👍 this looks good to go out whenever, just need @noahwc's approval

2025-05-28 17:18 UTC, noahwc approved these changes

2025-05-28 17:23 UTC, 00salmon commented
(note to self) update changelog date before launch when we can

2025-05-30 22:29 UTC, 00salmon approved these changes
✅

2025-05-30 22:30 UTC, merged