[Mint] Feature enforcement
saasquatch/program-tools pull request #398
Opened 2024-04-25 22:26 UTC by 00salmon

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

- Jira issue number: (PUT IT HERE)
- Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run (if applicable)
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist

### Code review

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2024-05-28 23:28 UTC, noahwc commented on packages/mint-components/package.json
> +    "@raisins/stencil-docs-target": "^1.0.2-3",
Move to a stable version

2024-05-28 23:29 UTC, noahwc commented on packages/mint-components/src/components/sqm-leaderboard/Leaderboard.stories.tsx
> +const tag = "Contact" + link + "about upgrading your plan";
Needs a real link, should be a template string for proper spacing between link and text

2024-05-28 23:35 UTC, noahwc commented on packages/mint-components/src/components/sqm-leaderboard/sqm-leaderboard-view.tsx
> +      <div>Leaderboards</div>
Does this header have the right styling?

2024-05-28 23:35 UTC, noahwc commented on packages/mint-components/src/components/sqm-rewards-table/RewardsTableCell.stories.tsx
> +    // AL: TODO
Flagging TODO

2024-05-28 23:36 UTC, noahwc reviewed
Just want to double check that all the new UI strings have gone through copy review too

2024-06-03 21:15 UTC, 00salmon commented on packages/vanilla-components/package.json
> +  "version": "1.2.9-4",
revert these changes - vanilla-components are updated in a different branch for feature enforcement

2024-06-03 21:19 UTC, 00salmon commented on packages/mint-components/src/components/sqm-popup-container/sqm-popup-container.tsx
> +   * Hide Powered by Impact.com link
```suggestion
   * Show Powered by Impact.com link
```

2024-06-03 21:19 UTC, 00salmon commented on packages/mint-components/src/components/sqm-popup-container/sqm-popup-container.tsx
> +   * @uiName Hide powered by
The label was reversed without any of the logic being reversed, this is causing it to show up when "Hide Powered By" is true
it needs to stay as "Show Powered By""
(same problem in vanilla-components PR)

2024-06-24 18:29 UTC, Locrian24 requested changes
Just needs official `@raisins/stencil-docs-target` version once it's published

2024-06-24 18:40 UTC, Locrian24 commented on packages/mint-components/package.json
> +    "@raisins/stencil-docs-target": "^1.0.2-3",
flagges for release

2024-06-26 22:48 UTC, Locrian24 submitted a review, later dismissed
Ready for deploy

2024-06-27 22:27 UTC, Locrian24 approved these changes

2024-07-03 22:07 UTC, Locrian24 submitted a review, later dismissed

2024-07-03 23:04 UTC, Locrian24 approved these changes

2024-07-03 23:04 UTC, merged