Promo codes
saasquatch/program-tools pull request #427
Opened 2024-12-02 23:25 UTC by 00salmon

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

- Jira issue number: (PUT IT HERE)
- Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run (if applicable)
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist

### Code review

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2024-12-20 23:05 UTC, DerekSiemens commented on packages/mint-components/src/components/sqm-referral-codes/ReferralCodes.feature
> +    Scenario: User is notified if the currently viewed promo code has been used already
Is this viewed or copied? I thought this was copied

2024-12-20 23:06 UTC, DerekSiemens commented on packages/mint-components/src/components/sqm-referral-codes/ReferralCodes.feature
> +            | EMAIL       |
Just flagging that clicking on any of these share medium buttons needs to count as being copied

2024-12-20 23:13 UTC, DerekSiemens commented on packages/mint-components/src/components/sqm-referral-codes/ReferralCodes.feature
> +    Scenario: User is notified if the currently viewed promo code has been used already
But we should have a spec that explicitly says we hide used codes

2025-01-16 06:03 UTC, Ultha258 approved these changes

2025-01-16 23:13 UTC, 00salmon commented on packages/mint-components/src/components/sqm-referral-codes/ReferralCodes.feature
> +        Then the notification text is displayed
it's configurable, so i'm not sure if it should be in the spec or not

2025-01-16 23:15 UTC, 00salmon commented on packages/mint-components/src/components/sqm-referral-codes/ReferralCodes.feature
> +        Then the notification text is displayed
i'll add some examples to represent that 🙏

2025-02-06 18:31 UTC, Locrian24 commented on packages/mint-components/src/components/sqm-pagination/sqm-pagination.tsx
> +  @Prop() demoData?: DemoData<any>; // TODO: types
TODO

2025-02-06 18:31 UTC, zachharrison commented on packages/mint-components/src/components/sqm-pagination/sqm-pagination.tsx
> +  @Prop() demoData?: DemoData<any>; // TODO: types
Update types

2025-02-06 18:33 UTC, Locrian24 commented on packages/mint-components/src/components/sqm-referral-code/useReferralCode.tsx
> +  query ($programId: ID) {
I've had issues with batching and unnamed queries in the past. Prob best to give this a unique-ish name

2025-02-06 18:33 UTC, zachharrison commented on packages/mint-components/src/components/views/copy-text-view.tsx
> +  console.log("notification text is", props.notificationText);
Remove console.log

2025-02-06 18:34 UTC, zachharrison requested changes
Couple things to cleanup, but otherwise things look good to me

2025-02-06 18:36 UTC, Locrian24 commented on packages/mint-components/src/components/sqm-referral-code/useReferralCode.tsx
> +  const [setCopied, copiedRes] = useMutation(SET_CODE_COPIED);
```suggestion
  const [setCopied] = useMutation(SET_CODE_COPIED);
```

2025-02-06 18:38 UTC, Locrian24 commented on packages/mint-components/src/components/sqm-referral-codes/sqm-referral-codes-view.tsx
> +import { EmptyStateView } from "../sqm-empty/sqm-empty-view";
```suggestion
```

2025-02-06 18:39 UTC, Locrian24 commented on packages/mint-components/src/components/sqm-referral-codes/sqm-referral-codes.tsx
> + * @slots [{"name":"", "title":"Promo Codes Content"}]
@slots seem incomplete

2025-02-06 18:39 UTC, Locrian24 commented on packages/mint-components/src/components/sqm-referral-codes/sqm-referral-codes.tsx
> +    console.log(props);
```suggestion
```

2025-02-06 18:41 UTC, Locrian24 commented on packages/mint-components/src/components/sqm-referral-codes/useReferralCodes.tsx
> +  console.log({ referralData, states });
```suggestion
```

2025-02-06 18:41 UTC, Locrian24 commented on packages/mint-components/src/components/sqm-referral-codes/useReferralCodes.tsx
> +      // onNext: () => callbacks.setCurrentPage(states.currentPage + 1),
```suggestion
```

2025-02-06 18:45 UTC, Locrian24 commented on packages/mint-components/CHANGELOG.md
> +  - SAM TODO
TODO

2025-02-06 18:47 UTC, Locrian24 commented on packages/mint-components/package.json
> -  "version": "1.11.0",
Flagging pre-release

2025-02-06 18:49 UTC, Locrian24 commented
Remove `sqm-pagination.feature`

2025-02-06 22:52 UTC, 00salmon commented on packages/mint-components/src/components/sqm-referral-codes/sqm-referral-codes.tsx
> + * @slots [{"name":"", "title":"Promo Codes Content"}]
In this case it looks like the loading and empty state are hard-coded and imported, might be a question of whether we should support both

2025-02-06 23:06 UTC, 00salmon commented on packages/mint-components/src/components/sqm-referral-codes/sqm-referral-codes.tsx
> +      ></sqm-empty>
this empty state is not translatable

2025-02-18 23:04 UTC, zachharrison approved these changes
Looks good to me.

2025-02-18 23:33 UTC, merged